version: '3.8'

services:
  style-bert-vits2-webtrain:
    build:
      context: .
      dockerfile: Dockerfile.webtrain
    volumes:
      - ./Data:/app/Data
      - ./inputs:/app/inputs
      - ./model_assets:/app/model_assets
    ports:
      - "7860:7860"
      - "7861:7861"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - CUDA_VISIBLE_DEVICES=0
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]