version: '3.8'

services:
  style-bert-vits2-webtrain:
    build:
      context: .
      dockerfile: Dockerfile.webtrain
    volumes:
      - ./Data:/app/Data
    ports:
      - "7860:7860"
      - "7861:7861"
      - "8080:8080"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - CUDA_VISIBLE_DEVICES=0
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]